.Dd November 16, 2012
.Dt SPIPE 1
.Os
.Sh NAME
.Nm spipe
.Nd spiped client utility
.Sh SYNOPSIS
.Nm
.Fl t Ar target_socket
.Fl k Ar key_file
.Op Fl f
.Op Fl o Ar connection_timeout
.Sh OPTIONS
.Bl -tag -width indent
.It Fl t Ar target_socket
Address to which
.Nm
should connect.
.It Fl k Ar key_file
Use the provided key file to authenticate and encrypt.
.It Fl f
Use fast/weak handshaking: This reduces the CPU time spent in the
initial connection setup, at the expense of losing perfect forward
secrecy.
.It Fl o Ar connection_timeout
Timeout, in seconds, after which an attempt to connect to the target
or a protocol handshake will be aborted (and the connection dropped)
if not completed.
Defaults to 5s.
.El
.Sh SEE ALSO
.Xr spiped 1
